name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: input
    id: go_version
    attributes:
      label: Go version
      placeholder: "go version go1.22.0 darwin/arm64"
  - type: input
    id: node_version
    attributes:
      label: Node version
      placeholder: "v20.11.0"
  - type: input
    id: docker_version
    attributes:
      label: Docker version
      placeholder: "Docker 24.0.7"
